/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 *TEMA PT ACASA
 * Tabela users cu
 *  #id
 *  username
 *  parola
 * (va contine utilizatorii)
 * 
 * magazin
 *  #id
 *  nume
 *  adresa
 * 
 * produs
 *  #id
 *  nume
 *  pret
 * 
 * itemi
 *  #id
 *  serie
 *  produs FK
 *  state (care poate fi 0 = in depozit;
 *                      1 = in magazin
 *  magazin FK
 *                      2 = vandut;)
 * 
 * Caseta de Login: User, Pass
 * Caseta Main:
 *      Optiuni -> Add Magazin
 *              -> Add Produs
 *              -> Afisare Produse -> Fereastra noua in care vedem toate produsele intr-o lista
 *                                  -> la click dreapta -> Add item -> deschide o fereastra cu state-ul IMPLICIT in depozit
 *                                                      -> Sterge produs
 * La click-dreapta pe lista magazin - > popup -> Adauga item -> Fereastra noua cu o lista tuturor itemilor care se afla in depozit
 *                                                                  si un buton cu textul ADAUGA IN MAGAZIN -> la apasare pune acei itemi in MAGAZINul respectiv
 *                                              -> Vizualizare item din magazin -> Deschide o fereastra a itemilor din MAGAZIN, de unde
 *                                                                                  similar modului in care itemii sunt pusi in magazin,
 *                                                                                  vor fi scosi din magazin iar statementul va fi VANDUT                    
 * 
 */

package gui;

import controllers.MainController;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.AngajatDB;
import model.DepartamentDB;
import model.UserDB;

/**
 *
 * @author student
 */
public class MainFrame extends javax.swing.JFrame {
    
    private UserDB user; // userul curent logat
    private DefaultListModel model1;
    private DefaultListModel model2;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(UserDB user) {
        this.user = user;
        initComponents();
        
        model1 = new DefaultListModel();
        jList1.setModel(model1);
        
        model2 = new DefaultListModel();
        jList2.setModel(model2);
        
        setLocationRelativeTo(null);
        afisareDepartamente();
    }
    
    private void afisareDepartamente(){
        model1.clear();
        List<DepartamentDB> departamente = MainController.getInstance().getDepartamente(user);
        
        for(DepartamentDB d: departamente){
            model1.addElement(d);
        }
    }
    
    private void afisareAngajati(DepartamentDB d){
        model2.clear();
        List<AngajatDB> angajati = MainController.getInstance().getAngajati(d);
        for(AngajatDB a: angajati){
            model2.addElement(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("Adauga angajat");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Afisare angajati");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jMenu1.setText("Options");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Adauga departament");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String nume = JOptionPane.showInputDialog("Departament:");
        MainController.getInstance().adaugaDepartament(nume, user);
        afisareDepartamente();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if(evt.getButton() == MouseEvent.BUTTON3 && jList1.getSelectedIndex() != -1){
            jPopupMenu1.show(jList1, evt.getX(), evt.getY()); // va afisa popup-meniul
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       String nume = JOptionPane.showInputDialog("Angajat:");
       DepartamentDB d = (DepartamentDB) jList1.getSelectedValue();
       MainController.getInstance().adaugaAngajati(nume, d);
       
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
